WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/Create.cshtml.cs
using _01_Framework.Application;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.Products
{
    public class CreateModel : PageModel
    {
        string Message;
        public CreateProduct Command;
        public SelectList Category;

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IAuthHelper _authHelper;

        public CreateModel(IAuthHelper authHelper
            , IProductCategoryApplication productCategoryApplication
            , IProductApplication productApplication)
        {
            _authHelper = authHelper;
            _productCategoryApplication = productCategoryApplication;
            _productApplication = productApplication;
        }

        public void OnGet()
        {
            Category = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        }

        public IActionResult OnPost(CreateProduct command)
        {
            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            var slug = command.Name;
            slug.Slugify();
            command.Slug= slug;
            command.AccountId = account.Id;

            var result = _productApplication.CreateProduct(command);
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/Edit.cshtml.cs
using _01_Framework.Application;
using BlogManagement.Application;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.Products
{
    public class Edit : PageModel
    {
        string Message;
        public EditProduct Command;
        public SelectList Category;

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IAuthHelper _authHelper;

        public Edit(IAuthHelper authHelper
            , IProductCategoryApplication productCategoryApplication
            , IProductApplication productApplication)
        {
            _authHelper = authHelper;
            _productCategoryApplication = productCategoryApplication;
            _productApplication = productApplication;
        }

        public void OnGet(long Id)
        {
            Command = _productApplication.GetDetails(Id);
            Category = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditProduct command , long id)
        {
            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            command.Id = id;
            var slug = command.Name;
            slug.Slugify();
            command.Slug= slug;
            command.AccountId = account.Id;

            var result = _productApplication.EditProduct(command);
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/Index.cshtml.cs
using _01_Framework.Application;
using _01_Framework.Infrastructure;
using InventoryManagement.Application.Contracts.Inventory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;
using ShopsManagement.Configuration.Permissions;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.Products
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }
        public ProductSearchModel SearchModel;
        public List<ProductViewModel> Product { get; set; }
        public SelectList ProductCategories;

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IAuthHelper _authHelper;

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication, IAuthHelper authHelper)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
            _authHelper = authHelper;
        }
        [NeedsPermission(ShopsPermissions.ListProduct)]

        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
            Product = _productApplication.Search(searchModel);

        }

        public IActionResult OnGetEdit(long id)
        {
            var Product = _productApplication.GetDetails(id);
            if(Product == null)
                return Page();

            Product.Categories = _productCategoryApplication.GetProductCategories();

            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            Product.AccountId = account.Id;
            return Partial("Edit", Product);
        }
        public IActionResult OnGetEditFileProduct(long id)
        {
            var Product = _productApplication.GetDetails(id);
            if (Product == null)
                return Page();
            var command = new EditFileProduct()
            {
                Id = Product.Id,
            };
            return Partial("EditFileProduct" , command);
        }
        public IActionResult OnPostEditFileProduct(EditFileProduct command) 
        {
            var result = _productApplication.EditFileProduct(command);
            if (result.IsSuccessful)
            {
                return new JsonResult(result);
            }
            Message = result.Message;
            return Page();
        }

        public IActionResult OnGetEditPictureProduct(long id)
        {
            var Product = _productApplication.GetDetails(id);
            if (Product == null)
                return Page();
            var command = new EditPictureProduct()
            {
                Id = Product.Id,
            };
            return Partial("EditPictureProduct", command);
        }
        public IActionResult OnPostEditPictureProduct(EditPictureProduct command)
        {
            var result = _productApplication.EditPictureProduct(command);
            if (result.IsSuccessful)
            {
                return new JsonResult(result);
            }
            Message = result.Message;
            return Page();
        }
        [NeedsPermission(ShopsPermissions.EditProduct)]

        public IActionResult OnPostEdit(EditProduct command)
        {
            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            command.AccountId = account.Id;
            var result = _productApplication.EditProduct(command);
            if (result.IsSuccessful)
            {
                return new JsonResult(result);
            }
            Message = result.Message;
            return Page();

        }


        public IActionResult OnGetRemove(long id)
        {
            var reault = _productApplication.Delete(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");


        }
        public IActionResult OnGetRestore(long id)
        {
            var reault = _productApplication.Restore(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/Requests/Product/Detail.cshtml.cs
using _01_Framework.Application;
using BlogManagement.Application;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.Requests.Product
{
    public class DetailModel : PageModel
    {
        string Message;
        public EditProduct Command;

        private readonly IProductApplication _productApplication;
        private readonly IAuthHelper _authHelper;

        public DetailModel(IAuthHelper authHelper
            , IProductCategoryApplication productCategoryApplication
            , IProductApplication productApplication)
        {
            _authHelper = authHelper;
            _productApplication = productApplication;
        }

        public void OnGet(long id)
        {
            Command = _productApplication.GetDetails(id);
        }

    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/Requests/Product/Index.cshtml.cs
using _01_Framework.Application;
using _01_Framework.Infrastructure;
using InventoryManagement.Application.Contracts.Inventory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;
using ShopsManagement.Configuration.Permissions;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.Requests.Product
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }
        public ProductSearchModel SearchModel;
        public List<ProductViewModel> Product { get; set; }
        public SelectList ProductCategories;

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IAuthHelper _authHelper;

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication, IAuthHelper authHelper)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
            _authHelper = authHelper;
        }
        [NeedsPermission(ShopsPermissions.ListProduct)]

        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
            Product = _productApplication.Search(searchModel);

        }

        public IActionResult OnGetPublish(long id)
        {
            var reault = _productApplication.Published(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetDownload(string FileProduct)
        {
            
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "AdminTheme", "UploadPicture", FileProduct);
            if (!System.IO.File.Exists(filePath))
            {
                return NotFound(); // اگر فایل وجود نداشته باشد
            }
            var contentType = "application/octet-stream"; // نوع محتوا برای دانلود
            return File(System.IO.File.ReadAllBytes(filePath), contentType, FileProduct);
        }
        public IActionResult OnGetReject(long id)
        {
            var reault = _productApplication.RejectProduct(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetDetails(long id)
        {
            var Product = _productApplication.GetDetails(id);
            if (Product == null)
                return Page();


            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            Product.AccountId = account.Id;
            return Partial("Details", Product);
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/Requests/Product/Detail.cshtml
@page
@model WeMarket.ServiceHost.Areas.Admin.Pages.Requests.Product.DetailModel
@{
    Layout = "Shared/_Layout";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">توضیحات محصول : @Model.Command.Name</h3>
            </div>
            <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group no-margin">
                                <label asp-for="@Model.Command.ShortDescription" class="control-label">توضیحات کوتاه</label>
                                <textarea class="form-control autogrow" asp-for="@Model.Command.ShortDescription" onchange="fillField('ShortDescription', 'MetaDescription')"
                                          style="overflow: hidden; word-wrap: break-word; resize: horizontal; height: 104px;"></textarea>
                                <span asp-validation-for="@Model.Command.ShortDescription" class="error"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group no-margin">
                                <label asp-for="@Model.Command.Description" class="control-label">توضیحات</label>
                                <textarea class="form-control" id="BodyContent" asp-for="@Model.Command.Description"></textarea>
                                <span asp-validation-for="@Model.Command.Description" class="error"></span>
                            </div>
                        </div>
                    </div>
                    <a asp-page="./Index" class="btn btn-danger waves-effect waves-light m-b-5">بازگشت</a>
            </div>
        </div>
    </div>
</div>

WeMarket.ServiceHost/Areas/Admin/Pages/Requests/Product/Index.cshtml
@page
@model WeMarket.ServiceHost.Areas.Admin.Pages.Requests.Product.IndexModel

@{
    ViewData["Title"] = "درخواست های محصولات";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["Title"]</h4>
        <p class="pull-left">
            <a asp-page="/ProductsManagement/Products/Index" class="btn btn-success btn-lg">صفحه محصولات</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در محصول ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name"></label>
                        <input class="form-control" asp-for="SearchModel.Name" placeholder="نام محصول">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ShortDescription"></label>
                        <input class="form-control" asp-for="SearchModel.ShortDescription" placeholder="توضیحات کوتاه">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست محصول ها (@Model.Product.Where(x=>x.IsPublished==false).Count())</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام </th>
                                    <th>توضیح کامل</th>
                                    <th>آیدی کاربر</th>
                                    <th>فایل ضمیمه شده</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Product.Where(x=>x.IsPublished==false))
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/AdminTheme/UploadPicture/@item.Picture" style="width: 70px; height: 70px" alt="@item.PictureAlt" title="@item.PictureTitle" />
                                        </td>
                                        <td>@item.Name</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5"
                                              asp-page="Detail" asp-route-id="@item.Id">
                                                <i class="fa fa-edit"></i> نمایش توضیحات
                                            </a>
                                        </td>
                                        <td>@item.Accounts</td>
                                        <td>
                                            @if (!string.IsNullOrWhiteSpace(item.FileProduct))
                                            {
                                                <p class="text-success">دارد</p>
                                            }
                                            else
                                            {
                                            <p class="text-danger">ندارد</p>
                                            }
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            @if (item.IsPublished == false)
                                            {
                                                <a class="btn btn-success waves-effect waves-light m-b-5" asp-page-handler="Publish" asp-page="./Index" asp-route-id="@item.Id">
                                                    <i class="md md-check"></i> تایید
                                                </a>
                                                @if (!string.IsNullOrWhiteSpace(item.FileProduct))
                                                {
                                                    <a class="btn btn-warning waves-effect waves-light m-b-5" asp-page-handler="Download" asp-page="./Index" asp-route-FileProduct="@item.FileProduct">
                                                        <i class="md md-file-download"></i> دانلود فایل ضمیمه
                                                    </a>
                                                }

                                                <a class="btn btn-danger waves-effect waves-light m-b-5" asp-page-handler="Reject" asp-page="./Index" asp-route-id="@item.Id">
                                                    <i class="md md-error"></i> رد کردن
                                                </a>
                                            }
                                        </td>


                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}