WeMarket.ServiceHost/Areas/Admin/Pages/AccountsManagement/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.AccountsManagement.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }
        
        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/AccountsManagement/Role/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using _01_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.AccountsManagement.Role
{
    public class EditModel : PageModel
    {
        public EditRole Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    var group = new SelectListGroup { Name = key };
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/Blog/Article/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.Blog.Article
{
    public class CreateModel : PageModel
    {
        public CreateArticle Command;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle command)
        { 
            var result = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/Blog/Article/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.Blog.Article
{
    public class EditModel : PageModel
    {
        public EditArticle Command;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditArticle command)
        {
            var result = _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/ProductCategory/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopsManagement.Application.Contracts.ProductCategory;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.ProductCategory
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }
        public ProductCategorySearchModel SearchModel;
        public List<ProductCategoryViewModel> ProductCategories;

        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }


        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }
        public JsonResult OnPostCreate(CreateProductCategory command)
        {
            var result = _productCategoryApplication.Create(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productCategory = _productCategoryApplication.GetDetails(id);
            return Partial("Edit", productCategory);
        }

        public JsonResult OnPostEdit(EditProductCategory command)
        {
            var result = _productCategoryApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetRemove(long id)
        {
            var reault = _productCategoryApplication.Delete(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");


        }
        public IActionResult OnGetRestore(long id)
        {
            var reault = _productCategoryApplication.Restore(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/Create.cshtml.cs
using _01_Framework.Application;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.Products
{
    public class CreateModel : PageModel
    {
        string Message;
        public CreateProduct Command;
        public SelectList Category;

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IAuthHelper _authHelper;

        public CreateModel(IAuthHelper authHelper
            , IProductCategoryApplication productCategoryApplication
            , IProductApplication productApplication)
        {
            _authHelper = authHelper;
            _productCategoryApplication = productCategoryApplication;
            _productApplication = productApplication;
        }

        public void OnGet()
        {
            Category = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        }

        public IActionResult OnPost(CreateProduct command)
        {
            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            var slug = command.Name;
            slug.Slugify();
            command.Slug= slug;
            command.AccountId = account.Id;

            var result = _productApplication.CreateProduct(command);
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/Edit.cshtml.cs
using _01_Framework.Application;
using BlogManagement.Application;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.Products
{
    public class Edit : PageModel
    {
        string Message;
        public EditProduct Command;
        public SelectList Category;

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IAuthHelper _authHelper;

        public Edit(IAuthHelper authHelper
            , IProductCategoryApplication productCategoryApplication
            , IProductApplication productApplication)
        {
            _authHelper = authHelper;
            _productCategoryApplication = productCategoryApplication;
            _productApplication = productApplication;
        }

        public void OnGet(long Id)
        {
            Command = _productApplication.GetDetails(Id);
            Category = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditProduct command , long id)
        {
            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            command.Id = id;
            var slug = command.Name;
            slug.Slugify();
            command.Slug= slug;
            command.AccountId = account.Id;

            var result = _productApplication.EditProduct(command);
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/Index.cshtml.cs
using _01_Framework.Application;
using _01_Framework.Infrastructure;
using InventoryManagement.Application.Contracts.Inventory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;
using ShopsManagement.Configuration.Permissions;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.Products
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }
        public ProductSearchModel SearchModel;
        public List<ProductViewModel> Product { get; set; }
        public SelectList ProductCategories;

        private readonly IProductApplication _productApplication;
        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IAuthHelper _authHelper;

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication, IAuthHelper authHelper)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
            _authHelper = authHelper;
        }
        [NeedsPermission(ShopsPermissions.ListProduct)]

        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
            Product = _productApplication.Search(searchModel);

        }

        public IActionResult OnGetEdit(long id)
        {
            var Product = _productApplication.GetDetails(id);
            if(Product == null)
                return Page();

            Product.Categories = _productCategoryApplication.GetProductCategories();

            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            Product.AccountId = account.Id;
            return Partial("Edit", Product);
        }
        public IActionResult OnGetEditFileProduct(long id)
        {
            var Product = _productApplication.GetDetails(id);
            if (Product == null)
                return Page();
            var command = new EditFileProduct()
            {
                Id = Product.Id,
            };
            return Partial("EditFileProduct" , command);
        }
        public IActionResult OnPostEditFileProduct(EditFileProduct command) 
        {
            var result = _productApplication.EditFileProduct(command);
            if (result.IsSuccessful)
            {
                return new JsonResult(result);
            }
            Message = result.Message;
            return Page();
        }

        public IActionResult OnGetEditPictureProduct(long id)
        {
            var Product = _productApplication.GetDetails(id);
            if (Product == null)
                return Page();
            var command = new EditPictureProduct()
            {
                Id = Product.Id,
            };
            return Partial("EditPictureProduct", command);
        }
        public IActionResult OnPostEditPictureProduct(EditPictureProduct command)
        {
            var result = _productApplication.EditPictureProduct(command);
            if (result.IsSuccessful)
            {
                return new JsonResult(result);
            }
            Message = result.Message;
            return Page();
        }
        [NeedsPermission(ShopsPermissions.EditProduct)]

        public IActionResult OnPostEdit(EditProduct command)
        {
            var account = _authHelper.CurrentAccountInfo();
            if (account == null)
                Message = ApplicationMessages.RecordNotFound;

            command.AccountId = account.Id;
            var result = _productApplication.EditProduct(command);
            if (result.IsSuccessful)
            {
                return new JsonResult(result);
            }
            Message = result.Message;
            return Page();

        }


        public IActionResult OnGetRemove(long id)
        {
            var reault = _productApplication.Delete(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");


        }
        public IActionResult OnGetRestore(long id)
        {
            var reault = _productApplication.Restore(id);
            if (!reault.IsSuccessful)
                Message = reault.Message;
            return RedirectToPage("./Index");
        }
    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/Requests/Product/Detail.cshtml.cs
using _01_Framework.Application;
using BlogManagement.Application;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopsManagement.Application.Contracts.ProductCategory;
using ShopsManagement.Application.Contracts.Products;

namespace WeMarket.ServiceHost.Areas.Admin.Pages.Requests.Product
{
    public class DetailModel : PageModel
    {
        string Message;
        public EditProduct Command;

        private readonly IProductApplication _productApplication;
        private readonly IAuthHelper _authHelper;

        public DetailModel(IAuthHelper authHelper
            , IProductCategoryApplication productCategoryApplication
            , IProductApplication productApplication)
        {
            _authHelper = authHelper;
            _productApplication = productApplication;
        }

        public void OnGet(long id)
        {
            Command = _productApplication.GetDetails(id);
        }

    }
}

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/EditFileProduct.cshtml
@using ShopsManagement.Application.Contracts.Products
@model EditFileProduct
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش : @Model.Id</h4>
</div>

<form asp-page="./Index" asp-page-handler="EditFileProduct"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <input type="hidden" name="Id" value="@Model.Id" />
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="FileProduct" class="control-label">فایل محصول</label>
                    <input type="file" class="form-control" asp-for="FileProduct">
                    <span asp-validation-for="FileProduct" class="error"></span>
                </div>
            </div>
        </div>

    </div>


    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/EditPictureProduct.cshtml
@using ShopsManagement.Application.Contracts.Products
@model EditPictureProduct
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش : @Model.Id</h4>
</div>

<form asp-page="./Index" asp-page-handler="EditPictureProduct"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <input type="hidden" name="Id" value="@Model.Id" />
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="PictureProduct" class="control-label">عکس محصول</label>
                    <input type="file" class="form-control" asp-for="PictureProduct">
                    <span asp-validation-for="PictureProduct" class="error"></span>
                </div>
            </div>
        </div>

    </div>


    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

WeMarket.ServiceHost/Areas/Admin/Pages/ProductsManagement/Products/Index.cshtml
@page
@model WeMarket.ServiceHost.Areas.Admin.Pages.ProductsManagement.Products.IndexModel

@{
    ViewData["Title"] = "مدیریت محصولات";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["Title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" asp-page="Create">ایجاد دستی محصول جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در محصول ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name"></label>
                        <input class="form-control" asp-for="SearchModel.Name" placeholder="نام محصول">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ShortDescription"></label>
                        <input class="form-control" asp-for="SearchModel.ShortDescription" placeholder="توضیحات کوتاه">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست محصول ها (@Model.Product.Count())</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام </th>
                                    <th>توضیح کوتاه</th>
                                    <th>آیدی کاربر</th>
                                    <th>فایل ضمیمه شده</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Product.Where(x=>x.IsPublished==true))
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/AdminTheme/UploadPicture/@item.Picture" style="width: 70px; height: 70px" alt="@item.PictureAlt" title="@item.PictureTitle" />
                                        </td>
                                        <td>@item.Name</td>
                                        <td>@item.ShortDescription</td>
                                        <td>@item.Accounts</td>
                                        <td>
                                            @if (!string.IsNullOrWhiteSpace(item.FileProduct))
                                            {
                                                <p class="text-success">دارد</p>
                                            }
                                            else
                                            {
                                            <p class="text-danger">ندارد</p>
                                            }
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            @if (item.IsDeleted == false)
                                            {
                                                <a class="btn btn-warning waves-effect waves-light m-b-5" asp-page="Edit" asp-route-id="@item.Id">
                                                    <i class="fa fa-edit"></i> ویرایش
                                                </a>
                                                <a class="btn btn-primary waves-effect waves-light m-b-5"
                                                   href="#showmodal=@Url.Page("./Index", "EditFileProduct", new { id = item.Id})">
                                                    <i class="fa fa-edit"></i> ویرایش فایل محصول
                                                </a>
                                                <a class="btn btn-primary waves-effect waves-light m-b-5"
                                                   href="#showmodal=@Url.Page("./Index", "EditPictureProduct", new { id = item.Id})">
                                                    <i class="fa fa-edit"></i> ویرایش عکس محصول
                                                </a>
                                                <a class="btn btn-danger waves-effect waves-light m-b-5" asp-page-handler="Remove" asp-page="./Index" asp-route-id="@item.Id">
                                                    <i class="md md-delete"></i> حذف
                                                </a>
                                            }
                                            else if (item.IsDeleted == true)
                                            {
                                                <a class="btn btn-warning waves-effect waves-light m-b-5" asp-page-handler="Restore" asp-page="./Index" asp-route-id="@item.Id">
                                                    <i class="md md-restore"></i> بازگردانی
                                                </a>
                                            }
                                        </td>


                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}